### ISSUE TITLE
Nice example - thanks.  Which License?

### ISSUE THREAD

**Issue by JamesParrott** [mrexodia/zig-cross#2]
Hey there.  This is a super useful snippet - thanks ever so much!

We'll definitely give you attribution (that goes without saying).  

But I don't see a license file.  Is it fair to assume there are no unusual terms we need to respect?

**Comment by mrexodia** [comment]
Feel free to use it for whatever purpose you like. Credit is not necessary, but appreciated. I think the code is too trivial to license honestly.

**Comment by JamesParrott** [comment]
Fantastic - thanks very much!  It's really helping port sDNA to Linux.

If you're interested:
https://github.com/fiftysevendegreesofrad/sdna_plus/actions/workflows/compile_dll_with_zig.yml
